### ISSUE TITLE
Where / how to start a security discussion?

### ISSUE THREAD

**Issue by poikilotherm** [duracloud/duracloud#144]
Hi y'all,

I would like to talk with you folks about a potential security issue.
Where is a good place to start this? (Looks like you are not providing a sec policy on Github)

(I know you offer a helpdesk and a contact form, but as this is not customer related, maybe you want to use some other place.)

This is related to https://github.com/IQSS/dataverse as we are a user of your Java libs.

**Comment by poikilotherm** [comment]
Can you please enable my account to create a ticket? o.bertuch@fz-juelich.de Thx

**Comment by bbranan** [comment]
Account invite sent and JIRA ticket has been created. Further discussion will be in JIRA, so I'll close this issue.
