### ISSUE TITLE
Introduce yourself (by commenting on this issue)

### ISSUE THREAD

**Issue by bbranan** [duracloud/duracloud#58]
Leave a comment below to say hello and let us know about your interests. (This is a good place to find collaborators!)

Use this example to help write your own introduction:

* **Your Name:** Bill Branan
* **Your Employer/Affiliation (if applicable):** [DuraSpace](http://duraspace.org)
* **What brings you to the DuraCloud project:** To make cloud storage more accessible (simpler to understand and use) and more suited to long-term data preservation
* **What would you like to work on for DuraCloud:** I want to help make the software solve real preservation challenges and help to build a community where we can all work together towards common goals

Remember that this issue is public, so please be careful when sharing personal information

**Comment by mayankjn34** [comment]
hii,
my name is Mayank jain 
i am a computer science student
I like the functioning and motive to develop duracloud 
i will like to contribute to this project as a java developer

**Comment by erintripp** [comment]
**Your Name:** Erin Tripp
**Your Employer/Affiliation (if applicable):** DuraSpace (hey Bill!!)
**What brings you to the DuraCloud project:** I'm excited to participate in a sprint, meet new people and I'll use it as an opportunity to work on a privacy and data protection policy for DuraCloud and help with other documentation/engagement tasks.
